language: python
sudo: required
python: 3.6
services: docker
branches:
  only:
    - master
install: 
  - pip3 install -r requirements.txt
before_script:
  # Tests Python (pytest installed by default)
  - pytest
script:
  # (Makefile) generics actions
  - make default