language: python
sudo: required
python: 2.7
services: docker
branches:
  only:
    - master
install: 
  - pip install -r myproject/requirements.txt
before_script:
  # Tests Python (pytest installed by default)
  - pytest
script:
  # (Makefile) generics actions
  - make default